name: Build
on: push
defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'
jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    steps:
      - name: Tools
        run: |
          mkdir .gha-bin
          echo "$PWD/.gha-bin" >> "$GITHUB_PATH"

          _download() {
            local target="$1"; shift
            local url="$1"; shift
            if command -v wget > /dev/null; then
              wget --timeout=5 -O "$target" "$url" --progress=dot:giga
            else
              curl -fL -o "$target" "$url"
            fi
          }

          # https://doi-janky.infosiftr.net/job/wip/job/crane
          _download ".gha-bin/crane" "https://doi-janky.infosiftr.net/job/wip/job/crane/lastSuccessfulBuild/artifact/crane-amd64"
          # TODO checksum verification ("checksums.txt")
          chmod +x ".gha-bin/crane"
          ".gha-bin/crane" version
        
      - name: test
        run: |
            crane pull --platform windows/amd64 mcr.microsoft.com/windows/server:ltsc2022 image.tar

      - name: Stage artifact
        uses: actions/upload-artifact@v4
        with:
            name: oci
            path: image.tar
            retention-days: 1